# Generated by Django 3.1.5 on 2021-01-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210120_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='post_category', to='posts.Gategory'),
        ),
    ]
