# Generated by Django 3.1.5 on 2021-01-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210121_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='next_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='previous_post',
        ),
    ]
